[package]
name = "rust-neural-net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
flate2 = "1.0.25"
png = "0.17.7"
rand = "0.8.4"
ndarray = "0.15.6"